### ISSUE TITLE
RO: PL: AT: IS: Issues with expired certificates.

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgc-testdata#208]
**Affected Country**: PL, AT, IS, RO

## Issue Description

Currently there is a problem in the validation application with PL certificates 4,5/ AT certificates 3 and 4(Also test certificate in onboarding)/ IS certificates 1 and 2/RO test certificate in onboarding. Upon scanning the QR codes, the validation application produces

2021-05-25 19:20:44.862 14909-14968/dgca.verifier.app.android D/CBOR: After expirationTime, expirationTime = 2021-05-25T10:38:52Z
2021-05-25 19:20:44.863 14909-14968/dgca.verifier.app.android E/CBOR: Error while decoding cbor
    java.lang.IllegalArgumentException: Expiration not correct: 2021-05-25T10:38:52Z
        at dgca.verifier.app.decoder.cbor.DefaultCborService.decode(DefaultCborService.kt:46)
        at dgca.verifier.app.android.verification.VerificationViewModel$decode$1$1.invokeSuspend(VerificationViewModel.kt:108)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

The screen after scanning:

![image](https://user-images.githubusercontent.com/84796166/119534161-47f2ce80-bd8f-11eb-808f-0d0b1b2907b8.png)

Steps to reproduce:
1) Scan the certificates mentioned above.

Expected result: Proper display of information and validity/invalidity of the certificate
Actual result: No information is being displayed and the certificate is invalid.

## Proposed Solution

Estonia is planning to use our own solution for scanning and verification and our developers have said that this is mostly an implementation question. But it seems that several countries are experiencing issues with this in testing  right now in the mobile verification application.

**Comment by asitplus-pteufl** [comment]
what i read from the data and from the app description, it is invalid because the CWT has expired. the testdata within the repository contains the validationclock property to indicate the validation time for testing. This is a problem for validation apps, since they will obviously take the current time for validation.
in general, I guess the test data repository will not be updated continuously, which is not a problem for automated tests, since they will use the validation clock, but it is a problem for standard apps (which do not read the validation clock property).

**Comment by NamingException** [comment]
This is the message from the RO verification app fork
![image](https://user-images.githubusercontent.com/4199801/119537743-09f7a980-bd93-11eb-93a3-bfd0388d218e.png)

The test data we uploaded was generated to be valid for a number of days and be accompanied by a validationClock. The test entry certificate was valid for 3 days I remember. 

We can upload new test entry certificates with longer period of validity I guess

**Comment by Mark-Selezenev** [comment]
It would be great if test entry certificates with longer period of validity are uploaded. As mentioned, this is a question of implementation but currently this would fix the - mark in onboarding from some of the countries.

**Comment by asitplus-pteufl** [comment]
yes, but no :-) the test certificates are at least - for us (AT) - created on the pre-production and test-systems, except for the data and the signature certificate they use the same properties as the prod. system, so having a long test validity here would change the test-system to non-real outputs.

for automated tests this is not a problem, since the validation clock property indicates when the validation occurs. @SchulzeStTSI what is your opinion on the data in the rep?

**Comment by asitplus-pteufl** [comment]
but again, this is a topic for the meeting on wednesday, since there are no clear guidelines on CWT validity

**Comment by SchulzeStTSI** [comment]
@asitplus-pteufl @Mark-Selezenev Good question. In the automated tests it should not be a problem, because the validation clock can be choosen as necessary. For "real world" tests, it's tricky, because the CWT EXP can be hit after some days. I think for this problem helps only a running QR Code generator in Country A which generates codes that are used for the validation in Country X. But this must be hosted by each memberstate, and all of them must be connected to the gateway tst/acc. This is for my opinion the next level of automated interop testing, but it needs a lot of effort to establish that. This is then a kind of "Testcloud".

**Comment by oleksandrsarapulovgl** [comment]
@Mark-Selezenev could you please point me to the QR from description: "Scan the certificates mentioned above."? Can't find it so far

**Comment by oleksandrsarapulovgl** [comment]
@Mark-Selezenev Could you please test on latest Android version? I Tested QRs and non is crashing for me

**Comment by oleksandrsarapulovgl** [comment]
![PL-5](https://user-images.githubusercontent.com/82441124/119654360-0adf1880-be31-11eb-991c-9dfcaa956a0b.png)
![PL-4](https://user-images.githubusercontent.com/82441124/119654362-0b77af00-be31-11eb-8fa5-aa9fad3788ea.png)
![IS-2](https://user-images.githubusercontent.com/82441124/119654363-0b77af00-be31-11eb-83a4-868f8eb8f4a4.png)
![IS-1](https://user-images.githubusercontent.com/82441124/119654365-0c104580-be31-11eb-9d21-6ad6eec6cd36.png)
![Uploading AT-4.png…]()

**Comment by NamingException** [comment]
I've uploaded new test certificate on confluence valid for 90 days. The ones on github will remain the same

**Comment by Mark-Selezenev** [comment]
@oleksandrsarapulovgl Which country are you from :) ?

**Comment by oleksandrsarapulovgl** [comment]
Ukraine)

**Comment by daniel-eder** [comment]
#219 fixes this issue for IS, not for all affected countries

**Comment by rafalgra** [comment]
PL improved the test data: #195
